
import type { Metadata } from "next";
import "./globals.css";
import { Montserrat} from "next/font/google";


const font_1 = Montserrat({
  subsets: ['latin'],
});

// const font_2 = Inter({
//   subsets: ['latin']
// })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font_1.className}>
        {children}
      </body>
    </html>
  );
}
